executable            = batch_BDT_input_v3/ele_flat2to100_PU200/run_harvest.sh
arguments             = $(ClusterID) $(JOB_ID)
output                = batch_BDT_input_v3/ele_flat2to100_PU200/logs/harvest_$(JOB_ID).$(ClusterId).$(ProcId).out
error                 = batch_BDT_input_v3/ele_flat2to100_PU200/logs/harvest_$(JOB_ID).$(ClusterId).$(ProcId).err
log                   = batch_BDT_input_v3/ele_flat2to100_PU200/logs/condor.harvest.$(ClusterId).log
+JobFlavour           = "tomorrow"

RequestCpus = 3

transfer_input_files  = batch_BDT_input_v3/ele_flat2to100_PU200/../ntuple-tools.tar.gz

transfer_output_files   = ""
queue
