executable            = batch_BDT_input_v1/ele_flat2to100_PU200/run_batch_hadd.sh
arguments             = $(ClusterID) $(ProcId)
output                = batch_BDT_input_v1/ele_flat2to100_PU200/logs/hadd.$(ClusterId).$(ProcId).out
error                 = batch_BDT_input_v1/ele_flat2to100_PU200/logs/hadd.$(ClusterId).$(ProcId).err
log                   = batch_BDT_input_v1/ele_flat2to100_PU200/logs/condor_hadd.$(ClusterId).log

+MaxRuntime = 14400
RequestCpus = 5

transfer_input_files  = batch_BDT_input_v1/ele_flat2to100_PU200/copy_files.sh
+PostCmd              = "copy_files.sh"
+PostArguments        = "$(ClusterID) $(JOB_ID) false"

+AccountingGroup = "group_u_CMST3.all"



transfer_output_files   = ""
queue
